ALTER TABLE expenses ADD COLUMN period_months INTEGER DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN period_type TEXT DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS incomes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  month_id INTEGER NOT NULL REFERENCES months(id) ON DELETE CASCADE,
  asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  amount REAL NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  month_id INTEGER NOT NULL REFERENCES months(id) ON DELETE CASCADE,
  expense_id INTEGER REFERENCES expenses(id) ON DELETE SET NULL,
  date TEXT NOT NULL,
  name TEXT NOT NULL,
  amount REAL NOT NULL DEFAULT 0,
  note TEXT,
  created_at INTEGER NOT NULL
);
